# ======================================================= #
#                         _  _                  _         #
#         _   _  __ _ ___(_)| |_ ___  _ __ ___ | |        #
#        | | | |/ _` |_  / || __/ _ \| '_ ` _ \| |        #
#        | |_| | (_| |/ /| || || (_) | | | | | | |        #
#         \__, |\__,_/___|_(_)__\___/|_| |_| |_|_|        #
#         |___/                                           #
#                  Yazi Configuration File                #
# ======================================================= #

# Documentation: https://yazi-rs.github.io/docs/configuration/overview

[mgr]
show_hidden = true

sort_by = "natural"
sort_translit = true
sort_dir_first = true
